app_home:
    path: /
    controller: App\Controller\HomeController::home
app_contact:
    path: /contact
    controller: App\Controller\HomeController::contact
app_about:
    path: /about
    controller: App\Controller\HomeController::about


